### ISSUE TITLE
geodesic?

### ISSUE THREAD

**Issue by morganherlocker** [Turfjs/turf-hex-grid#10]
Seems like this could work with geodesic calculations using turf-destination. This would remove the stretching reported in #9 .

**Comment by jseppi** [comment]
Should this be an option or the default behavior? If it is default, should non-geodesic be an option?

**Comment by morganherlocker** [comment]
I would say default and only option.

**Comment by morganherlocker** [comment]
Coordinates shift relative to the distance at the bottom of the grid. I think this is a good balance between equal-area-ness and speed expectations. Happy to revisit if necessary
