### ISSUE TITLE
radius and lon/lat

### ISSUE THREAD

**Issue by jvail** [Turfjs/turf-hex-grid#15]
It seems to me that the hexgrid is overstretched in y direction because of the radius in longitudes. I suppose the y in the hexagon function should use cellHeight / 2 instead of radius:

```javascript
var y = center[1] + cellHeight / 2 * sines[i];
```

**Comment by jseppi** [comment]
@jvail yes, I think adjusting to use `cellHeight` instead of `radius` would make the hexagons appear less stretched. Would you be interested in putting together a pull request with this change?

**Comment by jvail** [comment]
@jseppi sure

**Comment by jseppi** [comment]
Closed by f28e6def365664316c554fc46d092fe738d18192
