### ISSUE TITLE
Clarify what the input cell size is and simplify/cleanup calculations

### ISSUE THREAD

**Issue by jseppi** [Turfjs/turf-hex-grid#17]
I think it is unclear what the input cell size relates to in terms of the size of the output hexagons.
Also, as @jvail pointed out, the section of initial calculations about heights, width, adjustments, etc. is a bit messy and unclear -- it should be cleaned up and the code better documented.

**Comment by tmcw** [comment]
-> https://github.com/Turfjs/turf/issues/358
