### ISSUE TITLE
stretched hexagon

### ISSUE THREAD

**Issue by aperfectsquare** [Turfjs/turf-hex-grid#9]
Hi, it seems that the hexagon are stretched (not equilateral). I'll go deep in the code in the next days to see if i can correct this issue

**Comment by jseppi** [comment]
The hexes appear stretched probably because they are being visualized in a map in the mercator projection, which distorts area (especially the further north and south you go).

**Comment by morganherlocker** [comment]
see https://github.com/Turfjs/turf-hex-grid/issues/10#issuecomment-76034498
